spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unity?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&charset=utf8
    username: yuzhou
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: UnityHikariCP
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 5
      idle-timeout: 600000

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

  redis:
    database: 0
    timeout: 5000
    host: localhost
    port: 16379
    password:
      # 连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-wait: 10000
        max-idle: 15
        min-idle: 1
        max-active: 20

  thymeleaf:
    cache: false
    encoding: UTF-8

mybatis:
  mapper-locations: classpath*:sql/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl