CREATE TABLE SYS_CONFIG
(
    CONFIG_KEY      VARCHAR(64) NOT NULL,
    CONFIG_VALUE    VARCHAR(64) NOT NULL,
    TYPE            VARCHAR(64),
    PROFILE         VARCHAR(64),
    DESCRIPTION     VARCHAR(256),
    IS_SYSTEM       CHAR(1),
    IS_EDITABLE     CHAR(1),
    IS_NEED_RESTART CHAR(1),
    CREATED_AT      DATETIME    NOT NULL,
    CREATED_BY      VARCHAR(32) NOT NULL,
    UPDATED_AT      DATETIME    NOT NULL,
    UPDATED_BY      VARCHAR(32) NOT NULL,
    PRIMARY KEY CM_CONFIG_PK (CONFIG_KEY, CONFIG_VALUE)
);