CREATE TABLE USR_LOGIN_HIS
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID      VARCHAR(32) NOT NULL,
    ACCT_STATUS  CHAR(1)     NOT NULL,
    LOGIN_AT     DATETIME    NOT NULL,
    LOGIN_STATUS INT         NOT NULL,
    IP_ADDRESS   VARCHAR(32),
    BROWSER      VARCHAR(4000),
    CREATED_AT   DATETIME    NOT NULL,
    CREATED_BY   VARCHAR(32) NOT NULL,
    UPDATED_AT   DATETIME    NOT NULL,
    UPDATED_BY   VARCHAR(32) NOT NULL,
    INDEX LOGIN_HIS_IDX (USER_ID)
);


CREATE TABLE USR_UNKNOWN_LOGIN_HIS
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID    VARCHAR(32) NOT NULL,
    LOGIN_AT   DATETIME    NOT NULL,
    IP_ADDRESS VARCHAR(32),
    BROWSER    VARCHAR(4000),
    CREATED_AT DATETIME    NOT NULL,
    CREATED_BY VARCHAR(32) NOT NULL,
    UPDATED_AT DATETIME    NOT NULL,
    UPDATED_BY VARCHAR(32) NOT NULL
);